### ISSUE TITLE
vagrant destroy;vagrant up doesn't work

### ISSUE THREAD

**Issue by MatthewHager** [GetValkyrie/valkyrie#14]
It doesn't properly provision on vagrant up after a destroy.

**Comment by ergonlogic** [comment]
you need a 'vagrant reload --provision' too

**Comment by MatthewHager** [comment]
Is there a way on destroy to remove the semaphore and then on a subsequent up go ahead and run all the proper things? This used to work.

**Comment by ergonlogic** [comment]
vagrant destroy removes the semaphore file. Unfortunately, we can't call vagrant from within Vagrant. To set up NFS properly, we now have to run our provisioning as an alternative user, whereas previously, this only mattered later. I think the best bet is to have a project-level rebuild command to wrap the various vagrant commands.

**Comment by ergonlogic** [comment]
Since we've move to https://github.com/GetValkyrie/valkyrie-mount, this should be resolved.
