### ISSUE TITLE
Git Provision hangs Queue on Trusty host 

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#16]
fantastic project - congratulations, its wonderful to be finally using Aegir 3.x and its feeling extremely close now

however

I managed to install Valkyrie on my Trusty desktop and logged in to Aegir UI

everything verified and seemed fine

went to Git Provision Pressflow 7 but queue didnt run

deleted Tasks and Platform and tried Jon Pugh's Drupal 7 from drupalprojects on github, same deal, queue doesnt run

last I did a direct clone into the /var/aegir/platforms/drupal and tried a simple platform creation

no dice, queue still not running

**Comment by niccolox** [comment]
I was able to get the last Drupal 7 platform queue run by 

vagrant ssh
sudo su - aegir -s /bin/bash
cd ~/hostmaster-7.x-3.x/sites/valkyrie.local
drush hosting-queued

and then queue hang again so ran hosting-queued again for site install

not sure whats going on, or even if thats helping

its very late here

**Comment by niccolox** [comment]
tried again to git provision drupalprojects

queue hangs

aegir@valkyrie:~/hostmaster-7.x-3.x/sites/valkyrie.local$ drush cache-clear drush
PHP Fatal error:  Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc on line 127

Fatal error: Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc on line 127
Drush command terminated abnormally due to an unrecoverable error.                                                     [error]
Error: Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc, line 127
aegir@valkyrie:~/hostmaster-7.x-3.x/sites/valkyrie.local$ drush status
PHP Fatal error:  Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc on line 127

Fatal error: Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc on line 127
Drush command terminated abnormally due to an unrecoverable error.                                                     [error]
Error: Class 'Provision_Context_Valkyrie' not found in /var/aegir/.drush/provision/provision.context.inc, line 127

**Comment by niccolox** [comment]
very encouraging btw ... its real close ! I am done for the night

**Comment by ergonlogic** [comment]
Hi @niccolox,

Thanks for taking Valkyrie for a spin. Unfortunately, I introduced a bug last week and, due to client work, haven't had a chance to debug it properly. Thankfully, I've cleared my docket, and plan on working though this today. In the mean time, commit 300a7058 should  be safe.

**Comment by ergonlogic** [comment]
The underlying issue here has to do with how we generate aliases for use on the host machine. We do so via Aegir in the VM, writing them to a path that's mounted from the host via NFS. We then add a search path to the user's `~/.drushrc.php`. Most of this is actually handled by https://github.com/GetValkyrie/valkyrie-drush-aliases.

Generating the aliases themselves happens in Valkyrie. What appears to be happening is that the `@hostmaster` alias itself is getting re-written using the Valkyrie context-type. I believe it's our use of a backend_invoke(), whereas we may have to just call the command directly via an exec().

**Comment by ergonlogic** [comment]
Closing in favour of #33

**Comment by niccolox** [comment]
works now
