### ISSUE TITLE
msg: Destination directory /var/aegir/.ssh does not exist

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#29]
==> valkyrie: failed: [localhost] => {"checksum": "f27a62a8aab7f0a689a9778769487│·bceed161368", "failed": true}                                                   │·==> valkyrie: msg: Destination directory /var/aegir/.ssh does not exist         │·==> valkyrie:                                                                   │·==> valkyrie: FATAL: all hosts have already failed -- aborting                  │·==> valkyrie:                                                                   │·==> valkyrie: PLAY RECAP ******************************************************_│·**_*********\*                                                                   │·==> valkyrie:            to retry, use: --limit @/root/site.retry               │·==> valkyrie:                                                                   │·==> valkyrie: localhost                  : ok=55   changed=31   unreachable=0   │· failed=1                                                                       │·The SSH command responded with a non-zero exit status. Vagrant                  │·assumes that this means the command failed. The output for this command         │·should be in the log above. Please read the output to determine what            │·went wrong.

**Comment by niccolox** [comment]
this is repeatable and I think this is where I am stuck... looks like an Aegir playbook problem?

==> valkyrie: ^[[0;32mok: [localhost] => {"changed": false, "stat": {"atime": 1425974447.716511, "checksum": "f27a62a8aab7f0a689a9778769487bceed161368", "ctime": 1425974$
==> valkyrie:
==> valkyrie: TASK: [getvalkyrie.valkyrie | Allow SSH as the 'aegir' user] ******************
==> valkyrie: ^[[0;34m<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=zsalovdnsxsyxftcbhgcqytgxojgmhwf] password: " -u aegir /bin/sh -c '"'$
==> valkyrie: ^[[0;34m<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1425975776.29-104158544551769 && chmod a+rx /tmp/ansible-tmp-1425975776.29-1041585445$
==> valkyrie: ^[[0;34m<localhost> PUT /vagrant/.valkyrie/ssh/authorized_keys TO /tmp/ansible-tmp-1425975776.29-104158544551769/source^[[0m
==> valkyrie: ^[[0;34m<localhost> EXEC ['/bin/sh', '-c', 'chmod a+r /tmp/ansible-tmp-1425975776.29-104158544551769/source']^[[0m
==> valkyrie: ^[[0;34m<localhost> PUT /tmp/tmpAB9EwV TO /tmp/ansible-tmp-1425975776.29-104158544551769/copy^[[0m
==> valkyrie: ^[[0;34m<localhost> EXEC ['/bin/sh', '-c', 'chmod a+r /tmp/ansible-tmp-1425975776.29-104158544551769/copy']^[[0m
==> valkyrie: ^[[0;34m<localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=lfltgrvxbfbzndsylgiylwflnoxggkhh] password: " -u aegir /bin/sh -c '"'$
==> valkyrie: ^[[0;34m<localhost> EXEC ['/bin/sh', '-c', 'rm -rf /tmp/ansible-tmp-1425975776.29-104158544551769/ >/dev/null 2>&1']^[[0m
==> valkyrie: ^[[0;31mfailed: [localhost] => {"checksum": "f27a62a8aab7f0a689a9778769487bceed161368", "failed": true}^[[0m
==> valkyrie: ^[[0;31mmsg: Destination directory /var/aegir/.ssh does not exist^[[0m
==> valkyrie: ^[[0;31m
==> valkyrie: FATAL: all hosts have already failed -- aborting^[[0m
==> valkyrie:
==> valkyrie: PLAY RECAP ********************************************************************
==> valkyrie:            to retry, use: --limit @/root/site.retry
==> valkyrie:

**Comment by ghost** [comment]
To pass through, create a `.ssh` directory in `/var/aegir/`, owned by `aegir:aegir`.
Then, reload your vm with `vagrant reload --provision`.

**Comment by ergonlogic** [comment]
This should be fixed with recent work on the Valkyrie ansible role. Re-open if it's still an issue.
