### ISSUE TITLE
Add command to print the ssh key

### ISSUE THREAD

**Issue by MatthewHager** [GetValkyrie/valkyrie#3]
Would be awesome because I keep needing to cat `.valkyrie/ssh/id_rsa.pub | pbcopy`. Would be great to be able to `drush vsk | pbcopy`.

**Comment by ergonlogic** [comment]
why are you pastebinning this key?

**Comment by MatthewHager** [comment]
So I can paste it into gitlab for the deploy key. It's not pastebin, that puts it in my clipboard.

**Comment by ergonlogic** [comment]
I think what you need here is a shell alias:

```
alias vsk='cat .valkyrie/ssh/id_rsa.pub | pbcopy'
```

I'd rather figure out a way to register the keys directly with gitlab/github's API.

**Comment by MatthewHager** [comment]
OK, just close this out with a wontfix.
