### ISSUE TITLE
Map web group to host GID fails

### ISSUE THREAD

**Issue by ghost** [GetValkyrie/valkyrie#31]
Branch 0.4.x, HEAD

[peuc@sz6 valkyrie]$ vagrant up
Bringing machine 'valkyrie' up with 'virtualbox' provider...
==> valkyrie: Checking if box 'ubuntu/trusty64' is up to date...
==> valkyrie: VirtualBox VM is already running.
==> valkyrie: Fixing NFS user/group mapping.
    valkyrie: Setting up SSH access for the 'ubuntu' user.
    valkyrie: Refreshing SSH connection, to login as 'ubuntu'.
    valkyrie: Installing Ansible from sources.
    valkyrie: Running Ansible playbook to re-map users and groups.
==> valkyrie: 
==> valkyrie: PLAY [localhost] *************************************************************\* 
==> valkyrie: 
==> valkyrie: GATHERING FACTS **************************************************************\* 
==> valkyrie: ok: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [Move the 'dialout' group out of the way (OSX hosts).] *****************\* 
==> valkyrie: skipping: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [Re-map group ownership of any files owned by 'dialout' group (OSX hosts).] **\* 
==> valkyrie: skipping: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [Move the 'vagrant' group out of the way (GNU/Linux hosts).] ***********\* 
==> valkyrie: ok: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [Move the 'vagrant' user out of the way (GNU/Linux hosts).] ************\* 
==> valkyrie: ok: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [Map web group to host GID] ********************************************\* 
==> valkyrie: failed: [localhost] => {"failed": true, "name": "www-data"}
==> valkyrie: msg: groupmod: GID '100' already exists
==> valkyrie:  
==> valkyrie: 
==> valkyrie: FATAL: all hosts have already failed -- aborting  
==> valkyrie: 
==> valkyrie: PLAY RECAP *******************************************************************\* 
==> valkyrie:            to retry, use: --limit @/root/mount.retry
==> valkyrie: localhost                  : ok=3    changed=0    unreachable=0    failed=1  
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!                                                               

PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook /tmp/mount.yml -i /tmp/inventory --connection=local --sudo --extra-vars "host_os=x86_64-linux host_gid=100 host_uid=1000 "                                             

Stdout from the command:                                                                                          

PLAY [localhost] *************************************************************\*                                   

GATHERING FACTS **************************************************************\*  
ok: [localhost]

TASK: [Move the 'dialout' group out of the way (OSX hosts).] *****************\* 
skipping: [localhost]

TASK: [Re-map group ownership of any files owned by 'dialout' group (OSX hosts).] **\* 
skipping: [localhost]

TASK: [Move the 'vagrant' group out of the way (GNU/Linux hosts).] ***********\* 
ok: [localhost]

TASK: [Move the 'vagrant' user out of the way (GNU/Linux hosts).] ************\* 
ok: [localhost]

TASK: [Map web group to host GID] ********************************************\* 
failed: [localhost] => {"failed": true, "name": "www-data"}
msg: groupmod: GID '100' already exists

FATAL: all hosts have already failed -- aborting                                                                  

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/mount.retry

localhost                  : ok=3    changed=0    unreachable=0    failed=1   

Stderr from the command:

**Comment by ergonlogic** [comment]
Interesting. I'd taken a shortcut, and assumed that the host user's gid would be above 1000. We have logic to move an existing group out of the way for OSX hosts. So we should probably just generalize that.

**Comment by ergonlogic** [comment]
I opened an issue in the appropriate queue for this: https://github.com/GetValkyrie/valkyrie-mount/issues/2. I'll work on it over there.
