### ISSUE TITLE
Valkyrie & Aegir 3 at nyccamp.org 2015?

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#32]
hi

there is an email circulating about nycamp 2015 and Aegir getting some space at the Devops summit

I argued in that email that nycamp could become the US event home of Aegir ... and it should be a regular thing

can we do this?

its close to Montreal .. relatively short flight from Europe... would be a good thing to bootstrap, say the Aegir case-study of hosting the City of Copenhagen, into a UN sponsored agency using Aegir for Drupal hosting? 

there is SLAC also, https://www6.slac.stanford.edu/ they have thousands of sites, literally some of the oldest sites online, migrating into a multi-server, RHEL, Aegir custer... 

could be a good case for Aegir self-hosting government Drupal

NYC Camp 2015
A Week-long, Free Drupal Conference in NYC
July 13-19, 2015
http://nyccamp.org/

I really enjoyed the 2014 nycamp

its at the UN, is small, intimate, more of a camp, and NOT a trade show, but deeply technical

also felt less dominated by social networks revolving around the big Drupal shops and more fluid

**Comment by ergonlogic** [comment]
I'll certainly try to be there.

**Comment by ergonlogic** [comment]
So, yes, I'll be there, and present on Valkyrie, among other things. Hopefully, some other Poetic folks will be able to do the same.

**Comment by niccolox** [comment]
kind of presumptuous, but I made a post about this

http://niccolox.org/aegir-stream-devops-summit-nyccamp-org-un-july-2015/

**Comment by niccolox** [comment]
Inaugural Aegir Summit, nyccamp.org 2015

The worlds first dedicated Aegir Summit is in the New York City Drupal Camp, NycCamp.org, hosted within the United Nations in Manhattan, on Thursday-Sunday July 16-19 2015

http://aegirsummit.org/
