### ISSUE TITLE
aegir@valkyrie.local's password ? Ubuntu Trusty

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#36]
I can get all the way through to successful install and login to the Aegir web ui

however, I do get a confusing prompt on command line, which I dont understand

I sure dont know the password and actually thought aegir ran password-less

==> valkyrie: 
==> valkyrie: TASK: [getvalkyrie.valkyrie | Output the login link] *************************\* 
==> valkyrie: ok: [localhost] => {
==> valkyrie:     "var": {
==> valkyrie:         "aegir_login_link_output.stdout_lines": [
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////",
==> valkyrie:             "  You can access the front-end of your Aegir install at:",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "http://valkyrie.local/user/reset/1/1426376451/xfRWKAgjxpXkRU29efRUhKIV9BM3RWquDL11Lg0Hr84/login",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////"
==> valkyrie:         ]
==> valkyrie:     }
==> valkyrie: }
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.aegir | Clear Drush cache] ****************************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.aegir | Verify Aegir front-end] ***********************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.valkyrie | Reload Supervisor] *************************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: PLAY RECAP *******************************************************************\* 
==> valkyrie: localhost                  : ok=94   changed=57   unreachable=0    failed=0  
aegir@valkyrie.local's password:

**Comment by ergonlogic** [comment]
You're being prompted for a password at the end of a 'drush vnew'? Could it be that you don't have an RSA SSH key (~/.ssh/id_rsa.pub) to inject into the VM?

**Comment by niccolox** [comment]
am about to try this all again, but ... 

niccolox@server:~$ ls -alh ~/.ssh
total 24K
drwxr-xr-x  2 niccolox niccolox 4.0K Mar 15 11:09 .
drwxr-xr-x 31 niccolox niccolox 4.0K Mar 15 11:08 ..
-rw-------  1 niccolox niccolox  407 Mar  9 22:36 authorized_keys
-rwxr-xr-x  1 niccolox niccolox 3.2K Mar  9 01:05 id_rsa
-rwxr-xr-x  1 niccolox niccolox  744 Mar  9 01:05 id_rsa.pub
-rw-------  1 niccolox niccolox    0 Mar 15 11:09 known_hosts
-rw-------  1 niccolox niccolox  187 Mar 14 22:52 known_hosts.old

**Comment by niccolox** [comment]
ok, I did a vagrant destroy -, deleted the valkyrie project folder, deleted the .drush/valkyrie, cleared drush cache, checked exports

just realized I didnt delete the .valkyrie folder or checked/fix known_hosts

and tried again, same results

==> valkyrie: 
==> valkyrie: TASK: [getvalkyrie.valkyrie | Retrieve SSH public key] ***********************\* 
==> valkyrie: ok: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [getvalkyrie.valkyrie | Retrieve Aegir login link] *********************\* 
==> valkyrie: ok: [localhost]
==> valkyrie: 
==> valkyrie: TASK: [getvalkyrie.valkyrie | Output the deploy key] *************************\* 
==> valkyrie: ok: [localhost] => {
==> valkyrie:     "var": {
==> valkyrie:         "ssh_public_key_output.stdout_lines": [
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////",
==> valkyrie:             "  Add the following deploy key to your project on Github:",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBSfPXCjR8+9g0R3p42vJoEP1P2VB4iNOhlrtMiRHTukm7IrNc4B9Qcf/sISP1ZJX7nv5Q+Nz4LDg00l06Oj2dEXayQnneqw61Ot9dNxipuVPPotrMT0AUirSOnYsjqzOCz8KFr6vz8LReEQNSxwL3cnWfmVYqCw/IoJy9fJ3Mi8FIe/OYGzTlFkH2Rt+NHX78SAID+rD0DJBM0MvEi7foC6plVL7AElKyxA9+uLGAq9kR3cKLFZS7/ObVe84K/oHLo/Z68ArpYC9UUKENnMhf+hcSRyglVI36Zu2yUa+AIctq3JQF3xp0etyuw6P2cMWs5Bcwi/xJCL8mtwGE/gpJ Valkyrie deploy key",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////"
==> valkyrie:         ]
==> valkyrie:     }
==> valkyrie: }
==> valkyrie: 
==> valkyrie: TASK: [getvalkyrie.valkyrie | Output the login link] *************************\* 
==> valkyrie: ok: [localhost] => {
==> valkyrie:     "var": {
==> valkyrie:         "aegir_login_link_output.stdout_lines": [
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////",
==> valkyrie:             "  You can access the front-end of your Aegir install at:",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "http://valkyrie.local/user/reset/1/1426445832/DXPwHxXok69ZMsrHLpdZSZPpYRjDPdKPDrXZgpBicaA/login",
==> valkyrie:             "=============================================================================",
==> valkyrie:             "/////////////////////////////////////////////////////////////////////////////"
==> valkyrie:         ]
==> valkyrie:     }
==> valkyrie: }
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.aegir | Clear Drush cache] ****************************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.aegir | Verify Aegir front-end] ***********************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: NOTIFIED: [getvalkyrie.valkyrie | Reload Supervisor] *************************\* 
==> valkyrie: changed: [localhost]
==> valkyrie: 
==> valkyrie: PLAY RECAP *******************************************************************\* 
==> valkyrie: localhost                  : ok=94   changed=57   unreachable=0    failed=0  
aegir@valkyrie.local's password:

**Comment by niccolox** [comment]
can vagrant ssh into vm ok

aegir@valkyrie.local's password: 

[1]+  Stopped                 ~/.composer/vendor/drush/drush/drush vnew valkyrie
148 niccolox@arizmendi:~/Projects⟫ cd valkyrie/
niccolox@arizmendi:~/Projects/valkyrie⟫ vagrant ssh
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-46-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Sun Mar 15 18:49:25 UTC 2015
  
  System load:  0.59              Processes:           86
  Usage of /:   3.2% of 39.34GB   Users logged in:     0
  Memory usage: 12%               IP address for eth0: 10.0.2.15
  Swap usage:   0%
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/
  
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

vagrant@valkyrie:~$

**Comment by ergonlogic** [comment]
Can you check for warnings or errors earlier in the vnew log? Also, try 'drush sa' and look for the @v and @vm aliases. Then try 'drush @v ssh'.

**Comment by niccolox** [comment]
will do this later today/tonight

its not a show stopper, I can create sites now...

**Comment by niccolox** [comment]
figured this out, but haven't tested it on a fresh installation, might be a while

during a crazy late night installation session - while trying to troubleshoot an earlier version of Valkyrie

I reset my home directory permissions and opened them up

openssh ignores keys that have open permissions

so, did this

1 niccolox@server:~/Projects/⟫ chmod 600 /home/niccolox/.ssh/id_rsa  
niccolox@server:~/Projects/⟫ chmod -R 700 /home/niccolox/.ssh   

I expect next time I do a new Valkyrie project I wont have this issue

closing for now
