### ISSUE TITLE
git cloned failed and no folder is created in /var/aegir/platforms.. Trusty host

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#37]
I am getting a git cloned failed and no platform folder is created in /var/aegir/platforms

this fix doesnt work, there is no folder in platforms on guest or host 
https://github.com/GetValkyrie/valkyrie/issues/25

Cloning https://github.com/drupalprojects/drupal.git to /var/aegir/platforms/drupal-7-x-drupalprojects
Running git clone --recursive 'https://github.com/drupalprojects/drupal.git' '/var/aegir/platforms/drupal-7-x-drupalprojects' --branch '7.x'
Git clone failed! The specific errors are below: fatal: could not create work tree dir '/var/aegir/platforms/drupal-7-x-drupalprojects'.: No such file or directory

permissions.. 

closer and closer, good night

**Comment by ergonlogic** [comment]
What command are you running? Make sure that git sub modules are up-to-date in Valkyrie.

**Comment by niccolox** [comment]
destroyed and deleted, rebooted (as described https://github.com/GetValkyrie/valkyrie/issues/36#issuecomment-81201563) and was now able to deploy a platform using GIT and created a site

closing
