### ISSUE TITLE
Add Known Conflicts/Incompatibilities Section to Docs

### ISSUE THREAD

**Issue by RealLukeMartin** [GetValkyrie/valkyrie#49]
We discovered vagrant-sshfs 0.0.6 causes issues with the Ansible install on the vm. Will document this and anything like it moving forward

**Comment by ergonlogic** [comment]
vagrant-sshfs was dropped from Valkyrie a while ago. While we should definitely document specific versions of underlying OS, dependencies and such, I don't know that we need to document conflicts with un-related tools. I think issues here on github can be sufficient. These allow us to follow-up with work-arounds, and eventually fixes.
