### ISSUE TITLE
vagrant-triggers plugin not working, any work-around ?

### ISSUE THREAD

**Issue by chuxau** [GetValkyrie/valkyrie#58]
Hi,

In a bid to deploy valkyrie on a debian wheezy workstation, I tried to install vagrant-triggers plugin .. it installs without errors, but does not get recognized by vagrant .. and valkyrie is unable to work because of that.

Any alternatives to using vagrant-triggers ?

See [issue #41](https://github.com/emyl/vagrant-triggers/issues/41)

**Comment by chuxau** [comment]
I have been able to resolve my issues with vagrant-triggers .. was a ruby library problem ..

**Comment by ergonlogic** [comment]
I'm glad to hear it. FWIW, vagrant-triggers is only still in use to support vagrant-dns, which is OSX-specific. See #42.

**Comment by laymonk** [comment]
Oh, OK .. thats good to know .. so, I didnt really need it for debian install .. thanks for the update

**Comment by ergonlogic** [comment]
Actually, it'll still complain if you don't have it installed, but comenting out a couple lines in the Vagrantfile will solve that. We're planning on removing the vagrant-triggers dependency altogether, but that's pending #42.
