### ISSUE TITLE
drush dl valkyrie simplexml warning, release error

### ISSUE THREAD

**Issue by RealLukeMartin** [GetValkyrie/valkyrie#64]
➜  ~ drush dl valkyrie
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:72          [warning]
Failed to get available update data from                                                       [error]
https://updates.drupal.org/release-history/valkyrie/7.x
Could not download requested project(s).                                                       [error]

**Comment by RealLukeMartin** [comment]
I tried from head and also 0.4.2 release

**Comment by RealLukeMartin** [comment]
Noticed the change to release.sh just now, probably caused by that staging, let me know if this the root of the issue and I'll close this.

**Comment by ergonlogic** [comment]
The problem here might well be the version of Drush you are using. Projects with release starting with '0' weren't supported until a fix I added a couple months ago.

**Comment by RealLukeMartin** [comment]
It actually was an issue with drush 8.0-dev, dursh it seems to work now closing this issue.
