### ISSUE TITLE
{{ mysql_root_config_file }} throwing unsupported parameter during getvalkyrie.mysql role 

### ISSUE THREAD

**Issue by RealLukeMartin** [GetValkyrie/valkyrie#65]
==> valkyrie: TASK: [getvalkyrie.mysql | Update MySQL root password for localhost root account.] ***
==> valkyrie: failed: [localhost] => (item=valkyrie) => {"failed": true, "item": "valkyrie"}
==> valkyrie: msg: unsupported parameter for module: config_file
==> valkyrie: failed: [localhost] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
==> valkyrie: msg: unsupported parameter for module: config_file
==> valkyrie: failed: [localhost] => (item=::1) => {"failed": true, "item": "::1"}
==> valkyrie: msg: unsupported parameter for module: config_file
==> valkyrie: failed: [localhost] => (item=localhost) => {"failed": true, "item": "localhost"}
==> valkyrie: msg: unsupported parameter for module: config_file
==> valkyrie:
==> valkyrie: FATAL: all hosts have already failed -- aborting
==> valkyrie:
==> valkyrie: PLAY RECAP ********************************************************************
==> valkyrie:            to retry, use: --limit @/root/site.retry
==> valkyrie: localhost                  : ok=12   changed=6    unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
The external command could not be executed due to an application     [error]
error.
Illegal string offset 'site' backend.inc:1030                        [warning]
The command could not be executed successfully (returned: ssh: Could [error]
not resolve hostname valkyrie.val: nodename nor servname provided, or
not known
, code: 255)

**Comment by theodorosploumis** [comment]
I confirm that it works after the pull request applied.

**Comment by ghost** [comment]
I confirm the issue and this is a working solution to fix it.

**Comment by arosboro** [comment]
Solved the issue for me too
