### ISSUE TITLE
0.5.0 Release

### ISSUE THREAD

**Issue by ergonlogic** [GetValkyrie/valkyrie#75]
There have been some recent changes that warrant a new release. Foremost among these is the changes in OSX, back to a working network stack. This allows us to drop all extensions related to DNS, and just use Avahi for local domain resolution.

I'm also going to look at locking down versions for **everything**. Changes in community Ansible roles, Drush, and other such projects can break Valkyrie in ways that require non-trivial fixes.

I'm also going to consider building and publishing a vagrant box (or two). Most everything should just work, but the NFS trickery we do may cause some issues. Having a box for Linux and a box for OSX may help here, but there may be cleaner ways to do this.

**Comment by MatthewHager** [comment]
Awesome, great job everyone!

**Comment by ergonlogic** [comment]
Sorted through the issue queue, and came up with a couple quick fixes to integrate as part of [0.5.0](https://github.com/GetValkyrie/valkyrie/milestones/0.5.0). Also started on [0.6.0](https://github.com/GetValkyrie/valkyrie/milestones/0.6.0).

I pushed a [0.5.x branch](https://github.com/GetValkyrie/valkyrie/tree/0.5.x) too, which I've now made the default branch.

**Comment by ergonlogic** [comment]
I've cleaned up what I can. #78 indicated that `valkyrie-site-clone` is broken, which sucks. But I don't want to delay this release any further. Being a 0.x release, it should be understood that it isn't yet feature complete. <sigh />

**Comment by ergonlogic** [comment]
New release is up on d.o: https://www.drupal.org/node/2554077

**Comment by ergonlogic** [comment]
`drush dl valkyrie` works to update to 0.5.0 for me.
