### ISSUE TITLE
Virtualbox 5?

### ISSUE THREAD

**Issue by devekko** [GetValkyrie/valkyrie#81]
does this work on vb 5?

==> valkyrie: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.

**Comment by MatthewHager** [comment]
Are you running the very latest version? We just got VB5 support going in the last few commits.

**Comment by devekko** [comment]
==> valkyrie: Booting VM...                                                                               │·························
==> valkyrie: Waiting for machine to boot. This may take a few minutes...                                 │·························
The guest machine entered an invalid state while waiting for it                                           │·························
to boot. Valid states are 'starting, running'. The machine is in the                                      │·························
'poweroff' state. Please verify everything is configured                                                  │·························
properly and try again.                                                                                   │·························
                                                                                                          │·························
If the provider you're using has a GUI that comes with it,                                                │·························
it is often helpful to open that and watch the machine, since the                                         │·························
GUI often has more helpful error messages than Vagrant can retrieve.                                      │·························
For example, if you're using VirtualBox, run `vagrant up` while the                                       │·························
VirtualBox GUI is open.                                                                                   │·························
                                                                                                          │·························
The primary issue for this error is that the provider you're using                                        │·························
is not properly configured. This is very rarely a Vagrant issue.                                          │·························
The external command could not be executed due to an application     [error]                              │·························
error.                                                                                                    │·························
Illegal string offset 'site' backend.inc:1030                        [warning]                            │·························
The command could not be executed successfully (returned: ssh: Could [error]                              │·························
not resolve hostname valkyrie.local: Name or service not known                                            │·························
, code: 255)

**Comment by devekko** [comment]
its a fresh installation

vboxmanage --version                    5.0.2r102096  
Linux trusty-vagrant 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x│·························
86_64 GNU/Linux  
Vagrant 1.7.4

**Comment by devekko** [comment]
there was some change in Avahi or DNS or Bonjour in Valkyrie?

**Comment by devekko** [comment]
https://github.com/GetValkyrie/valkyrie/issues/75

**Comment by devekko** [comment]
I think its a general Virtualbox/Vagrant issue/// digging

**Comment by ergonlogic** [comment]
Vagrant itself isn't fully compatible with Virtualbox5, which appears to be rather unstable. There are a number of issues in the Vagrant queue about this. I recommend using the most recent Virtualbox 4.x for now.

For debugging purposes, you may want to try just launching a vanilla Vagrant project, and see if that works.

**Comment by devekko** [comment]
ok. both drupalvm and valkyrie break

will downgrade

**Comment by MatthewHager** [comment]
I know it works if you use the latest version of everything.
On Sat, Aug 29, 2015 at 6:49 PM Nicholas Roberts notifications@github.com
wrote:

> ok. both drupalvm and valkyrie break
> 
> will downgrade
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GetValkyrie/valkyrie/issues/81#issuecomment-136063162
> .
> 
> ## 
> 
> Thanks,

Matthew Hager, CEO
Poetic Systems
675 Bering Dr. Suite 725
Houston, TX 77057
office: (281) 531-4060
mobile: (281) 725-2380

**Comment by devekko** [comment]
I removed a layer of vm nesting and got vb 4.3 valkyrie working 

now vmware host for trusty desktop vm running vagrant

will test vb 5

**Comment by BrianGilbert** [comment]
Just reporting I've had no issues with VB5

**Comment by devekko** [comment]
I did a fresh Trusty install on my laptop, no Ubuntu Studio, no encrypted, nothing weird

it works with vb5
