### ISSUE TITLE
Add support for xdebug remote

### ISSUE THREAD

**Issue by MatthewHager** [GetValkyrie/valkyrie#9]
Would be awesome to use xdebug from the vm to the host. I've installed manually and gotten it to work with the following steps.

On the guest:

Install xdebug: `sudo apt-get install php5-xdebug`.
Configure xdebug `/etc/php5/apache2/conf.d/20-xdebug.ini` contents should be:

```
zend_extension=xdebug.so
xdebug.remote_enable=on
xdebug.remote_connect_back = on
```

Finally, apache will need to be restarted for this to take effect `sudo service apache2 restart`.

On the host (VIM):

Install vdebug (https://github.com/joonty/vdebug) using the method of choice (I used Vundle).
You'll need the following in order for the debugger to properly open a port for the guest to connect:
- let g:vdebug_options['server'] = “10.42.0.1"
- let g:vdebug_options['path_maps'] = {“/var/aegir/platforms/rune”: "/Users/matthew/Development/valkyrie/platforms/rune”}

The first setting tells vdebug to listen on a specific IP instead of localhost. The guest will attempt to connect back to the IP that the request originated from. The best way to find the IP of your host when it is making the request to the guest is to view the apache request logs. This will show you the IP of your host machine when it makes requests to the guest. You might need to change this setting.

The second setting is the path map that will allow vdebug to map files between the guest and host. This should go all the way to the platform on both the guest and host.

**Comment by ergonlogic** [comment]
Let's follow up in the PR, #53.
