### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by theodorosploumis** [GetValkyrie/valkyrie#93]
I have created a list of Drupal related tools: https://drupaltools.github.io/. Is this project active to add it on the list or not?

Thanks.

**Comment by ergonlogic** [comment]
I still use it semi-regularly. Bear in mind that it's built around Aegir. So the minimal development in this repo doesn't really reflect the overall velocity of the project.

**Comment by theodorosploumis** [comment]
OK added it. Thanks.
